export const projectDetails = [
  {
    id: 59,
    thumbnail: null,
    title: "To create a promo for Nutra World",
    startDate: "2023-09-21T00:00:00.000Z",
    dueDate: "2023-09-27T00:00:00.000Z",
    priority: 4,
    referenceVideo: null,
    createdAt: "2023-09-21T05:53:04.000Z",
    updatedAt: "2023-09-30T07:01:45.000Z",
    description:
      "Source the stocks from past events and blend them with script. Music should be very catchy and trendy.",
    attachment: [
      {
        id: 392,
        link: "https://www.youtube.com/results?search_query=hubstaff+demo",
        name: "Reference",
      },
    ],
    members: [
      {
        id: 105,
        name: "Darshn Jangam",
        email: "gauravjangam0000@gmail.com",
      },
      {
        id: 155,
        name: "Varun Shinde",
        email: "varunshinde273@gmail.com",
      },
      {
        id: 161,
        name: "Arpit Shrivastava",
        email: "arpit@scrobits.com",
      },
      {
        id: 156,
        name: "RaHUL patil",
        email: "rahulpatil221996@gmail.com",
      },
      {
        id: 158,
        name: "Sanket Nilakh",
        email: "sanket.nilakh.scrobits@gmail.com",
      },
      {
        id: 163,
        name: "Bhupesh Wankar",
        email: "bhupeshwankar20@gmail.com",
      },
      {
        id: 164,
        name: "Parth Dhruv",
        email: "parth@sadigital.in",
      },
    ],
    createdBy: {
      id: 1,
      name: "Abhijeet Gavali",
      email: "abhi@example.com",
    },
    updatedBy: {
      id: 1,
      name: "Abhijeet Gavali",
      email: "abhi@example.com",
    },
  },
];

export const boardDetails = [
  {
    name: "Pitch/Demo",
    cards: null,
    status: 1,
  },
  {
    name: "Script/Project on board",
    cards: [
      {
        id: 236,
        key: 0,
        title: "Script for Nutra World",
        todos: null,
        dueDate: "2023-09-26 00:00:00.000000",
        members: [
          {
            id: 156,
            name: "RaHUL patil",
            color: "01FFC0",
            email: "rahulpatil221996@gmail.com",
          },
          {
            id: 158,
            name: "Sanket Nilakh",
            color: "7DA507",
            email: "sanket.nilakh.scrobits@gmail.com",
          },
          {
            id: 163,
            name: "Bhupesh Wankar",
            color: "67215C",
            email: "bhupeshwankar20@gmail.com",
          },
          {
            id: 164,
            name: "Parth Dhruv",
            color: "CBB83C",
            email: "parth@sadigital.in",
          },
        ],
        priority: 4,
        createdAt: "2023-09-25 06:41:14.000000",
        createdBy: {
          id: 1,
          name: "Abhijeet Gavali",
          email: "abhi@example.com",
        },
        startDate: "2023-09-25 00:00:00.000000",
        updatedAt: "2023-10-03 13:26:12.000000",
        updatedBy: {
          id: 163,
          name: "Bhupesh Wankar",
          email: "bhupeshwankar20@gmail.com",
        },
        attachments: null,
        description: "jdffb",
      },
    ],
    status: 2,
  },
  {
    name: "Pre-Production",
    cards: null,
    status: 3,
  },
  {
    name: "Production/Shoot",
    cards: null,
    status: 4,
  },
  {
    name: "Post Production",
    cards: [
      {
        id: 235,
        key: null,
        title: "To create a promo for Nutra World",
        todos: null,
        dueDate: "2023-09-27 18:30:00.000000",
        members: [
          {
            id: 105,
            name: "Darshn Jangam",
            color: "45FCF4",
            email: "gauravjangam0000@gmail.com",
          },
          {
            id: 155,
            name: "Varun Shinde",
            color: "661DB2",
            email: "varunshinde273@gmail.com",
          },
          {
            id: 161,
            name: "Arpit Shrivastava",
            color: "951940",
            email: "arpit@scrobits.com",
          },
        ],
        priority: 3,
        createdAt: "2023-09-21 06:06:07.000000",
        createdBy: {
          id: 1,
          name: "Abhijeet Gavali",
          email: "abhi@example.com",
        },
        startDate: "2023-09-21 00:00:00.000000",
        updatedAt: "2023-09-21 06:14:55.000000",
        updatedBy: {
          id: 1,
          name: "Abhijeet Gavali",
          email: "abhi@example.com",
        },
        attachments: [
          {
            id: 391,
            link: "https://sa-media.fra1.digitaloceanspaces.com/lms_upload/png/1695276922045doc.png",
            name: "Screenshot 2023-09-14 at 7.52.12 PM.png",
          },
          {
            id: 393,
            link: "https://www.youtube.com/results?search_query=hubstaff+demo",
            name: "Reference",
          },
        ],
        description: "To create a promo for Nutra World",
      },
    ],
    status: 5,
  },
  {
    name: "Review",
    cards: null,
    status: 6,
  },
  {
    name: "Completed",
    cards: null,
    status: 7,
  },
  {
    name: "Discarded",
    cards: null,
    status: 8,
  },
];

export const allVendors = {
  result: [
    {
      id: 166,
      firstName: "Peter2",
      lastName: "Parker2",
      email: "mr.abhijeetgavali+test@gmail.com",
      mobile: 3728310749,
      profileUrl: null,
      designation: "",
      salesCrm: 0,
      proposalMaker: 0,
      LMS: 1,
      videoEstimater: 0,
      vendorManagment: 1,
      projectManagement: 1,
      vendor: 1,
      address: "some address",
      bankName: "BOI",
      accountHoldersName: "Peter Parker",
      accountNumber: 1234567890,
      accountType: "Savings",
      IFSC_Code: "BKI0533",
      location: "pune",
      vendorType: "business",
      level: 3,
      interests: "acting",
      title: "Creative artist",
      businessName: "Some awsome business",
      rating: 4.5,
      noOfTalents: 10,
      sourceOfVendor: 3,
      category: 2,
      commericialExpections: "12345",
      accessToCourse: 0,
      reference: "Abhijeet",
      color: "4E4C3D",
      createdAt: "2023-10-19T09:01:28.000Z",
      updatedAt: "2023-10-19T09:01:28.000Z",
      skillset: [
        {
          id: 187,
          name: "2D Explainer Videos",
        },
        {
          id: 188,
          name: "2D Animation",
        },
        {
          id: 189,
          name: "3D Modelling",
        },
        {
          id: 190,
          name: "3D Animation",
        },
      ],
      expertise: [
        {
          id: 187,
          name: "2D Explainer Videos",
        },
        {
          id: 188,
          name: "2D Animation",
        },
        {
          id: 189,
          name: "3D Modelling",
        },
        {
          id: 190,
          name: "3D Animation",
        },
      ],
      ongoingProjects: null,
      previouslyWorkedOn: null,
      createdBy: {
        id: 1,
        name: "Abhijeet Gavali",
        email: "abhi@example.com",
      },
      updatedBy: {
        id: 1,
        name: "Abhijeet Gavali",
        email: "abhi@example.com",
      },
    },
    {
      id: 165,
      firstName: "Parth",
      lastName: "Dhruv",
      email: "parthdhruv6@gmail.com",
      mobile: 9511878436,
      profileUrl: null,
      designation: "",
      salesCrm: 0,
      proposalMaker: 0,
      LMS: 1,
      videoEstimater: 0,
      vendorManagment: 1,
      projectManagement: 1,
      vendor: 1,
      address: null,
      bankName: null,
      accountHoldersName: null,
      accountNumber: null,
      accountType: null,
      IFSC_Code: null,
      location: "Nagpur",
      vendorType: "business",
      level: 2,
      interests: "Motion Graphics",
      title: "Graphic Designer",
      businessName: null,
      rating: 0,
      noOfTalents: null,
      sourceOfVendor: null,
      category: 4,
      commericialExpections: null,
      accessToCourse: 1,
      reference: null,
      color: "246CF1",
      createdAt: "2023-10-04T05:56:25.000Z",
      updatedAt: "2023-10-04T05:56:25.000Z",
      skillset: [
        {
          id: 185,
          name: "Video Editor",
        },
        {
          id: 186,
          name: "Motion Graphics",
        },
      ],
      expertise: [
        {
          id: 185,
          name: "Video Editor",
        },
        {
          id: 186,
          name: "Motion Graphics",
        },
      ],
      ongoingProjects: null,
      previouslyWorkedOn: null,
      createdBy: {
        id: 1,
        name: "Abhijeet Gavali",
        email: "abhi@example.com",
      },
      updatedBy: {
        id: 1,
        name: "Abhijeet Gavali",
        email: "abhi@example.com",
      },
    },
    {
      id: 164,
      firstName: "Parth",
      lastName: "Dhruv",
      email: "parth@sadigital.in",
      mobile: 8446992334,
      profileUrl: null,
      designation: "",
      salesCrm: 0,
      proposalMaker: 0,
      LMS: 1,
      videoEstimater: 0,
      vendorManagment: 0,
      projectManagement: 1,
      vendor: 1,
      address: null,
      bankName: null,
      accountHoldersName: null,
      accountNumber: null,
      accountType: null,
      IFSC_Code: null,
      location: "Nagpur",
      vendorType: "business",
      level: 3,
      interests: "Content Writing",
      title: "Self-Employed",
      businessName: null,
      rating: null,
      noOfTalents: null,
      sourceOfVendor: null,
      category: 2,
      commericialExpections: null,
      accessToCourse: 1,
      reference: null,
      color: "CBB83C",
      createdAt: "2023-10-04T05:44:17.000Z",
      updatedAt: "2023-10-04T05:44:17.000Z",
      skillset: [
        {
          id: 183,
          name: "Script Writing - English",
        },
        {
          id: 184,
          name: "Script Writing - Hindi",
        },
      ],
      expertise: [
        {
          id: 183,
          name: "Script Writing - English",
        },
        {
          id: 184,
          name: "Script Writing - Hindi",
        },
      ],
      ongoingProjects: [
        {
          id: 59,
          name: "To create a promo for Nutra World",
        },
      ],
      previouslyWorkedOn: null,
      createdBy: {
        id: 1,
        name: "Abhijeet Gavali",
        email: "abhi@example.com",
      },
      updatedBy: {
        id: 1,
        name: "Abhijeet Gavali",
        email: "abhi@example.com",
      },
    },
    {
      id: 163,
      firstName: "Bhupesh",
      lastName: "Wankar",
      email: "bhupeshwankar20@gmail.com",
      mobile: 8850210971,
      profileUrl: null,
      designation: "",
      salesCrm: 0,
      proposalMaker: 0,
      LMS: 1,
      videoEstimater: 0,
      vendorManagment: 0,
      projectManagement: 1,
      vendor: 1,
      address: null,
      bankName: null,
      accountHoldersName: null,
      accountNumber: null,
      accountType: null,
      IFSC_Code: null,
      location: "Nagpur",
      vendorType: "individual",
      level: 2,
      interests: "Corporate Videos",
      title: "Script Writer",
      businessName: null,
      rating: 5,
      noOfTalents: null,
      sourceOfVendor: null,
      category: 2,
      commericialExpections: null,
      accessToCourse: 1,
      reference: null,
      color: "67215C",
      createdAt: "2023-09-25T06:50:34.000Z",
      updatedAt: "2023-09-25T06:50:34.000Z",
      skillset: [
        {
          id: 182,
          name: "Script Writing - English",
        },
      ],
      expertise: [
        {
          id: 182,
          name: "Script Writing - English",
        },
      ],
      ongoingProjects: [
        {
          id: 59,
          name: "To create a promo for Nutra World",
        },
      ],
      previouslyWorkedOn: null,
      createdBy: {
        id: 1,
        name: "Abhijeet Gavali",
        email: "abhi@example.com",
      },
      updatedBy: {
        id: 1,
        name: "Abhijeet Gavali",
        email: "abhi@example.com",
      },
    },
    {
      id: 162,
      firstName: "Abraham",
      lastName: "Lincoln",
      email: "abl@gmail.com",
      mobile: 9876543210,
      profileUrl: null,
      designation: "",
      salesCrm: 0,
      proposalMaker: 0,
      LMS: 1,
      videoEstimater: 0,
      vendorManagment: 0,
      projectManagement: 1,
      vendor: 1,
      address: null,
      bankName: null,
      accountHoldersName: null,
      accountNumber: null,
      accountType: null,
      IFSC_Code: null,
      location: "Daman",
      vendorType: "individual",
      level: 4,
      interests: "Video Editing, Graphics Designing, Singing, Music",
      title: "Video Editor",
      businessName: null,
      rating: 4,
      noOfTalents: null,
      sourceOfVendor: null,
      category: 5,
      commericialExpections: null,
      accessToCourse: 1,
      reference: null,
      color: "2D53D0",
      createdAt: "2023-09-21T05:44:40.000Z",
      updatedAt: "2023-09-21T05:44:40.000Z",
      skillset: [
        {
          id: 179,
          name: "Video Editor",
        },
        {
          id: 180,
          name: "Motion Graphics",
        },
        {
          id: 181,
          name: "2D Animation",
        },
      ],
      expertise: [
        {
          id: 179,
          name: "Video Editor",
        },
        {
          id: 180,
          name: "Motion Graphics",
        },
        {
          id: 181,
          name: "2D Animation",
        },
      ],
      ongoingProjects: null,
      previouslyWorkedOn: null,
      createdBy: {
        id: 1,
        name: "Abhijeet Gavali",
        email: "abhi@example.com",
      },
      updatedBy: {
        id: 1,
        name: "Abhijeet Gavali",
        email: "abhi@example.com",
      },
    },
    {
      id: 161,
      firstName: "Arpit",
      lastName: "Shrivastava",
      email: "arpit@scrobits.com",
      mobile: 7020818025,
      profileUrl: null,
      designation: "",
      salesCrm: 0,
      proposalMaker: 0,
      LMS: 1,
      videoEstimater: 0,
      vendorManagment: 0,
      projectManagement: 1,
      vendor: 1,
      address: null,
      bankName: null,
      accountHoldersName: null,
      accountNumber: null,
      accountType: null,
      IFSC_Code: null,
      location: "mumbai",
      vendorType: "business",
      level: 2,
      interests: "asd, sed",
      title: "asd sds ",
      businessName: null,
      rating: 3,
      noOfTalents: null,
      sourceOfVendor: null,
      category: 2,
      commericialExpections: null,
      accessToCourse: 1,
      reference: null,
      color: "951940",
      createdAt: "2023-08-29T11:11:32.000Z",
      updatedAt: "2023-10-26T04:49:37.000Z",
      skillset: [
        {
          id: 178,
          name: "2D Animation",
        },
      ],
      expertise: [
        {
          id: 178,
          name: "2D Animation",
        },
      ],
      ongoingProjects: [
        {
          id: 45,
          name: "project ",
        },
        {
          id: 59,
          name: "To create a promo for Nutra World",
        },
      ],
      previouslyWorkedOn: null,
      createdBy: {
        id: 1,
        name: "Abhijeet Gavali",
        email: "abhi@example.com",
      },
      updatedBy: {
        id: 1,
        name: "Abhijeet Gavali",
        email: "abhi@example.com",
      },
    },
    {
      id: 158,
      firstName: "Sanket",
      lastName: "Nilakh",
      email: "sanket.nilakh.scrobits@gmail.com",
      mobile: 7387290306,
      profileUrl:
        "https://sa-media.fra1.digitaloceanspaces.com/lms_upload/png/1692766232812doc.png",
      designation: "",
      salesCrm: 0,
      proposalMaker: 0,
      LMS: 1,
      videoEstimater: 0,
      vendorManagment: 0,
      projectManagement: 1,
      vendor: 1,
      address: null,
      bankName: null,
      accountHoldersName: null,
      accountNumber: null,
      accountType: null,
      IFSC_Code: null,
      location: "pune",
      vendorType: "business",
      level: 3,
      interests: "nono",
      title: "YO YO",
      businessName: null,
      rating: 5,
      noOfTalents: null,
      sourceOfVendor: null,
      category: 4,
      commericialExpections: null,
      accessToCourse: 0,
      reference: null,
      color: "7DA507",
      createdAt: "2023-08-21T13:04:23.000Z",
      updatedAt: "2023-08-21T13:04:23.000Z",
      skillset: [
        {
          id: 174,
          name: "Video Editor",
        },
      ],
      expertise: [
        {
          id: 174,
          name: "Video Editor",
        },
      ],
      ongoingProjects: [
        {
          id: 44,
          name: "Test Project",
        },
        {
          id: 59,
          name: "To create a promo for Nutra World",
        },
      ],
      previouslyWorkedOn: null,
      createdBy: {
        id: 1,
        name: "Abhijeet Gavali",
        email: "abhi@example.com",
      },
      updatedBy: {
        id: 1,
        name: "Abhijeet Gavali",
        email: "abhi@example.com",
      },
    },
    {
      id: 156,
      firstName: "RaHUL",
      lastName: "patil",
      email: "rahulpatil221996@gmail.com",
      mobile: 7898565892,
      profileUrl:
        "https://sa-media.fra1.digitaloceanspaces.com/lms_upload/png/1692766232812doc.png",
      designation: "",
      salesCrm: 1,
      proposalMaker: 0,
      LMS: 1,
      videoEstimater: 0,
      vendorManagment: 0,
      projectManagement: 0,
      vendor: 1,
      address: null,
      bankName: null,
      accountHoldersName: null,
      accountNumber: null,
      accountType: null,
      IFSC_Code: null,
      location: "pune",
      vendorType: "business",
      level: 3,
      interests: "xdcfgvh",
      title: "op-ijh",
      businessName: null,
      rating: 3,
      noOfTalents: null,
      sourceOfVendor: null,
      category: 2,
      commericialExpections: null,
      accessToCourse: 0,
      reference: null,
      color: "01FFC0",
      createdAt: "2023-08-11T10:00:40.000Z",
      updatedAt: "2023-08-11T10:00:40.000Z",
      skillset: [
        {
          id: 172,
          name: "Video Shooting",
        },
      ],
      expertise: [
        {
          id: 172,
          name: "Video Shooting",
        },
      ],
      ongoingProjects: [
        {
          id: 59,
          name: "To create a promo for Nutra World",
        },
      ],
      previouslyWorkedOn: null,
      createdBy: {
        id: 1,
        name: "Abhijeet Gavali",
        email: "abhi@example.com",
      },
      updatedBy: {
        id: 1,
        name: "Abhijeet Gavali",
        email: "abhi@example.com",
      },
    },
    {
      id: 155,
      firstName: "Varun",
      lastName: "Shinde",
      email: "varunshinde273@gmail.com",
      mobile: 4536789227,
      profileUrl:
        "https://sa-media.fra1.digitaloceanspaces.com/lms_upload/png/1692766232812doc.png",
      designation: "",
      salesCrm: 0,
      proposalMaker: 0,
      LMS: 1,
      videoEstimater: 0,
      vendorManagment: 0,
      projectManagement: 0,
      vendor: 1,
      address: null,
      bankName: null,
      accountHoldersName: null,
      accountNumber: null,
      accountType: null,
      IFSC_Code: null,
      location: "pune",
      vendorType: "business",
      level: 3,
      interests: "asdf",
      title: "asdfvz",
      businessName: null,
      rating: 2.5,
      noOfTalents: null,
      sourceOfVendor: null,
      category: 2,
      commericialExpections: null,
      accessToCourse: 0,
      reference: null,
      color: "661DB2",
      createdAt: "2023-08-11T09:04:00.000Z",
      updatedAt: "2023-08-22T09:26:31.000Z",
      skillset: [
        {
          id: 171,
          name: "3D Modelling",
        },
      ],
      expertise: [
        {
          id: 171,
          name: "3D Modelling",
        },
      ],
      ongoingProjects: [
        {
          id: 42,
          name: "SA Digital ",
        },
        {
          id: 59,
          name: "To create a promo for Nutra World",
        },
      ],
      previouslyWorkedOn: null,
      createdBy: {
        id: 1,
        name: "Abhijeet Gavali",
        email: "abhi@example.com",
      },
      updatedBy: {
        id: 1,
        name: "Abhijeet Gavali",
        email: "abhi@example.com",
      },
    },
    {
      id: 154,
      firstName: "Gaurav",
      lastName: "Jangam",
      email: "gauravjangamgame@gmail.com",
      mobile: 9374351289,
      profileUrl:
        "https://sa-media.fra1.digitaloceanspaces.com/lms_upload/png/1692766232812doc.png",
      designation: "",
      salesCrm: 0,
      proposalMaker: 0,
      LMS: 1,
      videoEstimater: 0,
      vendorManagment: 0,
      projectManagement: 0,
      vendor: 1,
      address: null,
      bankName: null,
      accountHoldersName: null,
      accountNumber: null,
      accountType: null,
      IFSC_Code: null,
      location: "pune",
      vendorType: "business",
      level: 2,
      interests: "gvbhj",
      title: "new",
      businessName: null,
      rating: 5,
      noOfTalents: null,
      sourceOfVendor: null,
      category: 3,
      commericialExpections: null,
      accessToCourse: 0,
      reference: null,
      color: "D8B4EC",
      createdAt: "2023-08-11T08:53:30.000Z",
      updatedAt: "2023-08-11T08:53:30.000Z",
      skillset: [
        {
          id: 169,
          name: "3D Modelling",
        },
        {
          id: 170,
          name: "3D Animation",
        },
      ],
      expertise: [
        {
          id: 169,
          name: "3D Modelling",
        },
        {
          id: 170,
          name: "3D Animation",
        },
      ],
      ongoingProjects: [
        {
          id: 42,
          name: "SA Digital ",
        },
        {
          id: 44,
          name: "Test Project",
        },
        {
          id: 56,
          name: "Second last",
        },
      ],
      previouslyWorkedOn: null,
      createdBy: {
        id: 1,
        name: "Abhijeet Gavali",
        email: "abhi@example.com",
      },
      updatedBy: {
        id: 1,
        name: "Abhijeet Gavali",
        email: "abhi@example.com",
      },
    },
    {
      id: 126,
      firstName: "Peter2",
      lastName: "Parker2",
      email: "mr.abhijeetgavali+test2@gmail.com",
      mobile: 3728313749,
      profileUrl:
        "https://sa-media.fra1.digitaloceanspaces.com/lms_upload/png/1692766232812doc.png",
      designation: "",
      salesCrm: 0,
      proposalMaker: 0,
      LMS: 1,
      videoEstimater: 0,
      vendorManagment: 0,
      projectManagement: 0,
      vendor: 1,
      address: "some address",
      bankName: "BOI",
      accountHoldersName: "Peter Parker",
      accountNumber: 1234567890,
      accountType: "Savings",
      IFSC_Code: "BKI0533",
      location: "pune",
      vendorType: "business",
      level: 3,
      interests: "acting",
      title: "Creative artist",
      businessName: "Some awsome business",
      rating: 4.5,
      noOfTalents: 10,
      sourceOfVendor: 3,
      category: 2,
      commericialExpections: "12345",
      accessToCourse: 0,
      reference: "Abhijeet",
      color: "126DEF",
      createdAt: "2023-08-09T08:06:50.000Z",
      updatedAt: "2023-08-09T08:06:50.000Z",
      skillset: [
        {
          id: 87,
          name: "2D Explainer Videos",
        },
        {
          id: 88,
          name: "2D Animation",
        },
        {
          id: 89,
          name: "3D Modelling",
        },
        {
          id: 90,
          name: "3D Animation",
        },
      ],
      expertise: [
        {
          id: 87,
          name: "2D Explainer Videos",
        },
        {
          id: 88,
          name: "2D Animation",
        },
        {
          id: 89,
          name: "3D Modelling",
        },
        {
          id: 90,
          name: "3D Animation",
        },
      ],
      ongoingProjects: [
        {
          id: 42,
          name: "SA Digital ",
        },
        {
          id: 46,
          name: "Automation",
        },
        {
          id: 47,
          name: "HELOOOOOO",
        },
      ],
      previouslyWorkedOn: null,
      createdBy: {
        id: 1,
        name: "Abhijeet Gavali",
        email: "abhi@example.com",
      },
      updatedBy: {
        id: 1,
        name: "Abhijeet Gavali",
        email: "abhi@example.com",
      },
    },
    {
      id: 121,
      firstName: "Peter2",
      lastName: "Parker2",
      email: "abhijeetgavali.scrobits+2vendor@gmail.com",
      mobile: 3728523649,
      profileUrl:
        "https://sa-media.fra1.digitaloceanspaces.com/lms_upload/png/1692766232812doc.png",
      designation: "",
      salesCrm: 0,
      proposalMaker: 0,
      LMS: 1,
      videoEstimater: 0,
      vendorManagment: 0,
      projectManagement: 0,
      vendor: 1,
      address: "some address",
      bankName: "BOI",
      accountHoldersName: "Peter Parker",
      accountNumber: 1234567890,
      accountType: "Savings",
      IFSC_Code: "BKI0533",
      location: "pune",
      vendorType: "business",
      level: 3,
      interests: "acting",
      title: "Creative artist",
      businessName: "Some awsome business",
      rating: 4.5,
      noOfTalents: 10,
      sourceOfVendor: 3,
      category: 2,
      commericialExpections: "12345",
      accessToCourse: 0,
      reference: "Abhijeet",
      color: "121DEF",
      createdAt: "2023-08-08T16:55:41.000Z",
      updatedAt: "2023-08-08T16:55:41.000Z",
      skillset: [
        {
          id: 37,
          name: "2D Explainer Videos",
        },
        {
          id: 38,
          name: "2D Animation",
        },
        {
          id: 39,
          name: "3D Modelling",
        },
        {
          id: 40,
          name: "3D Animation",
        },
      ],
      expertise: [
        {
          id: 37,
          name: "2D Explainer Videos",
        },
        {
          id: 38,
          name: "2D Animation",
        },
        {
          id: 39,
          name: "3D Modelling",
        },
        {
          id: 40,
          name: "3D Animation",
        },
      ],
      ongoingProjects: [
        {
          id: 46,
          name: "Automation",
        },
        {
          id: 47,
          name: "HELOOOOOO",
        },
      ],
      previouslyWorkedOn: null,
      createdBy: {
        id: 1,
        name: "Abhijeet Gavali",
        email: "abhi@example.com",
      },
      updatedBy: {
        id: 1,
        name: "Abhijeet Gavali",
        email: "abhi@example.com",
      },
    },
    {
      id: 105,
      firstName: "Darshn",
      lastName: "Jangam",
      email: "gauravjangam0000@gmail.com",
      mobile: 8208552669,
      profileUrl:
        "https://sa-media.fra1.digitaloceanspaces.com/lms_upload/png/1692766232812doc.png",
      designation: "",
      salesCrm: 0,
      proposalMaker: 0,
      LMS: 0,
      videoEstimater: 0,
      vendorManagment: 1,
      projectManagement: 0,
      vendor: 1,
      address: null,
      bankName: null,
      accountHoldersName: null,
      accountNumber: null,
      accountType: null,
      IFSC_Code: null,
      location: "Nagar",
      vendorType: "business",
      level: 3,
      interests: "Yo new Interest",
      title: "New title",
      businessName: null,
      rating: 3.5,
      noOfTalents: 10,
      sourceOfVendor: null,
      category: 3,
      commericialExpections: null,
      accessToCourse: 0,
      reference: null,
      color: "45FCF4",
      createdAt: "2023-08-11T08:50:15.000Z",
      updatedAt: "2023-09-11T16:24:19.000Z",
      skillset: [
        {
          id: 168,
          name: "3D Animation",
        },
      ],
      expertise: [
        {
          id: 168,
          name: "3D Animation",
        },
      ],
      ongoingProjects: [
        {
          id: 42,
          name: "SA Digital ",
        },
        {
          id: 59,
          name: "To create a promo for Nutra World",
        },
      ],
      previouslyWorkedOn: [
        {
          id: 58,
          name: "scrbits video promo",
        },
      ],
      createdBy: {
        id: 1,
        name: "Abhijeet Gavali",
        email: "abhi@example.com",
      },
      updatedBy: {
        id: 1,
        name: "Abhijeet Gavali",
        email: "abhi@example.com",
      },
    },
    {
      id: 82,
      firstName: "Nikhil",
      lastName: "Patil",
      email: "nikhilpatil0973@gmail.com",
      mobile: 7028837895,
      profileUrl:
        "https://sa-media.fra1.digitaloceanspaces.com/lms_upload/png/1692766232812doc.png",
      designation: "QA",
      salesCrm: 1,
      proposalMaker: 1,
      LMS: 0,
      videoEstimater: 0,
      vendorManagment: 1,
      projectManagement: 0,
      vendor: 1,
      address: "qwuodol",
      bankName: "Maharashtra Bank",
      accountHoldersName: "Nikhil patil",
      accountNumber: 93289137,
      accountType: "Saving",
      IFSC_Code: "dww",
      location: "Balanagar",
      vendorType: "business",
      level: 1,
      interests: "edrfgh",
      title: "Second title demo",
      businessName: null,
      rating: 4,
      noOfTalents: 11,
      sourceOfVendor: 1,
      category: 1,
      commericialExpections: null,
      accessToCourse: 0,
      reference: "Friend",
      color: "D5ECA6",
      createdAt: "2023-08-23T07:23:27.000Z",
      updatedAt: "2023-09-11T05:02:48.000Z",
      skillset: [
        {
          id: 175,
          name: "2D Animation",
        },
      ],
      expertise: [
        {
          id: 175,
          name: "2D Animation",
        },
      ],
      ongoingProjects: [
        {
          id: 42,
          name: "SA Digital ",
        },
        {
          id: 56,
          name: "Second last",
        },
      ],
      previouslyWorkedOn: [
        {
          id: 58,
          name: "scrbits video promo",
        },
      ],
      createdBy: {
        id: 1,
        name: "Abhijeet Gavali",
        email: "abhi@example.com",
      },
      updatedBy: {
        id: 1,
        name: "Abhijeet Gavali",
        email: "abhi@example.com",
      },
    },
  ],
  count: 14,
};
